### ISSUE TITLE
suggestion: ImageOptim workflow

### ISSUE THREAD

**Issue by rizkysyazuli** [zenorocha/alfred-workflows#63]
very useful:
https://github.com/ramiroaraujo/alfred-image-optim-workflow

**Comment by zenorocha** [comment]
Thanks for the suggestion @rizkysyazuli! Just added it to the Extras wiki: https://github.com/zenorocha/alfred-workflows/wiki/Extras/_compare/8fc442cd547c6bff687df30b41cc890c692e4c5d%5E...8fc442cd547c6bff687df30b41cc890c692e4c5d
