### ISSUE TITLE
Install Script

### ISSUE THREAD

**Issue by chrisopedia** [zenorocha/alfred-workflows#65]
I've created an [install script](https://github.com/chrisopedia/alfred-workflows/blob/go/install) to make it easier for someone to install each individual workflow.  Not sure if you're interested in merging this in or just referencing my fork, but thought I'd let you know.

## Installation Instructions
```bash
bash -c "$(curl -#fL raw.github.com/chrisopedia/alfred-workflows/go/install)"
```

**Comment by yoaquim** [comment]
Hey Chris. Was looking for something like this for my base install script. Does it prompt you for each workflow, or just install all of'em? Thanks!

**Comment by chrisopedia** [comment]
@yoaquim it installs them all, but I could change it to prompt

**Comment by zenorocha** [comment]
Looks great @chrisopedia, good job! 

I'm pretty busy with other stuff and trying to maintain any code in this repo. 

Thanks anyways and sorry for the delay :/

**Comment by kgfnk** [comment]
川野さん


おはようございます。舟木です。


雪の影響で電車が遅れているため、
大分出社が遅れそうです。


申し訳ありませんが、よろしくお願いいたします。
