### ISSUE TITLE
iOS Simulator Filename Change

### ISSUE THREAD

**Issue by ritcheyer** [zenorocha/alfred-workflows#77]
The latest update of XCode changed the name of the simulators to the following:

```
/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app
/Applications/Xcode.app/Contents/Developer/Applications/Simulator (Watch).app
```

**Comment by zenorocha** [comment]
Thanks a lot for reporting and sorry for taking so long to reply @ritcheyer :/

A change on Alfred or Xcode now makes it possible to find it easily. Therefore, this workflow is no longer needed.

<img width="654" alt="screen shot 2016-04-07 at 9 20 44 am" src="https://cloud.githubusercontent.com/assets/398893/14358509/1d32b7ae-fca2-11e5-9a3c-2ac3e7bf4282.png">
