### ISSUE TITLE
Dash workflow should be installed via Dash 

### ISSUE THREAD

**Issue by nantas** [zenorocha/alfred-workflows#79]
Since it's maintained by Dash dev team, if installed from Dash->preference->integration, it will be automatically setup with existing docset and updated bash script.

Install with downloaded workflow file from your readme may result in 'Couldn't load Dash' error in Alfred search result list.

see https://github.com/Kapeli/Dash-Alfred-Workflow

**Comment by zenorocha** [comment]
Thanks for reporting @nantas!
