### ISSUE TITLE
VM doesn't seem to work

### ISSUE THREAD

**Issue by corysimmons** [zenorocha/alfred-workflows#83]
I have several VMs in VirtualBox. When I tried to use the workflow it shows the 1st option when you type `v`, but once you select it, it doesn't display any VMs or anything -- just a Google search. :\

I checked the author's GitHub and is doesn't seem very active.

**Comment by jcfranco** [comment]
FYI – this one works like a charm:

https://github.com/aiyodk/Alfred-Extensions/raw/master/AlfredApp_2.x/VirtualBox-Control/VirtualBox-Control.alfredworkflow

**Comment by corysimmons** [comment]
@jcfranco Awesome thank you. It does work. =)

**Comment by zenorocha** [comment]
Thanks @corysimmons for reporting and @jcfranco for pointing it out ;)
