### ISSUE TITLE
Colors not working in v2.8.3

### ISSUE THREAD

**Issue by fspoettel** [zenorocha/alfred-workflows#84]
The colors workflow is dysfunctional in v2.8.3 for me. I tried calling it by text input / with a hotkey and in both instances it does not seem to recognize any kind of input color.

**Comment by zenorocha** [comment]
Everything seems to be working fine here with Alfred v2.8.3 and Colors v2.0.2

<img width="654" alt="screen shot 2016-04-07 at 8 56 12 am" src="https://cloud.githubusercontent.com/assets/398893/14357706/a62a104c-fc9e-11e5-8015-8c7f01ef1e59.png">

**Comment by fspoettel** [comment]
![screen shot 2016-04-07 at 18 31 21](https://cloud.githubusercontent.com/assets/1682504/14358821/0e54e156-fcef-11e5-9ab0-cd3c0687b4e3.png)
Still erroring out for me with no useful information, but I guess the fault is somewhere in my setup.

**Comment by zenorocha** [comment]
It seems like another extension is conflicting with this one.

<img width="594" alt="screen shot 2016-04-07 at 9 38 35 am" src="https://cloud.githubusercontent.com/assets/398893/14359058/971c0140-fca4-11e5-9059-9de2551f1e54.png">

For more details, please fill an issue with the Color workflow author: https://github.com/TylerEich/Alfred-Extras

**Comment by fspoettel** [comment]
alright I'll try to find the error on my end. thanks for your help with this, much appreciated!
