### ISSUE TITLE
Can I Use not working with Alfred 3

### ISSUE THREAD

**Issue by iagomelanias** [zenorocha/alfred-workflows#86]
There is [a issue](https://github.com/willfarrell/alfred-caniuse-workflow/issues/13) submitted (and still not replied) in the `alfred-caniuse-workflow` repository about a bug which there are no results being displayed when using Alfred 3.

<img width="665" alt="captura de tela 2016-09-22 as 19 34 40" src="https://cloud.githubusercontent.com/assets/6279712/18768456/a276bb08-80fb-11e6-88e3-46c1051416b1.png">

An observation in the description of the workflow would be awesome.

**Comment by santosfilipe** [comment]
Hi,

Have you tested the workflow and it is not working for you?

I am using Alfred 3 with macOS Sierra and "Can I Use" is working flawlessly (maybe the issue was alredy fixed).

**Comment by iagomelanias** [comment]
Hello @santosfilipe. Yes, absolutely. This screenshot was made by myself while i was writing this issue.

So strange, here is not working even after reinstalling the workflow.

**Comment by iagomelanias** [comment]
[Fixed](https://github.com/willfarrell/alfred-caniuse-workflow/releases/tag/1.8).

**Comment by octavioamu** [comment]
This shouldn't be closed, the code need to be merged with the fixed one
