### ISSUE TITLE
Use git submodules instead of copying repositories

### ISSUE THREAD

**Issue by Tadaboody** [zenorocha/alfred-workflows#98]
Using [git submodules](https://git-scm.com/book/en/v2/Git-Tools-Submodules), we can easily keep all the workflows up to date.
There will need to be extra instructions to make sure that people looking to edit existing repos will `clone --recursive` and push the changes upstream to the original workflow repositories

**Comment by zenorocha** [comment]
Although I like that idea of removing the need for me to update them, I feel like git submodules are not very accessible for a lot of people. Besides that, there are some workflows which are not on git. So I think for now we'll keep doing like this. I appreciate the suggestion!

**Comment by Tadaboody** [comment]
Alternatively - how about automating the process with a script? Pulling the most recent release from the ones that are on git should be simple enough
